MyDjangoProject/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Path to home page
    path('', include('learning_logs.urls')),
]

MyDjangoProject/learning_log/learning_logs/urls.py
from django.urls import path

from learning_logs import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

MyDjangoProject/learning_log/learning_logs/models.py
from django.db import models

# Create your models here.
# https://docs.djangoproject.com/en/5.1/
# https://docs.djangoproject.com/en/4.1/topics/db/queries
# https://docs.djangoproject.com/en/4.1/ref/templates. 
# https://docs.djangoproject.com/en/4.1/topics/db/forms/
class Topic(models.Model):
    """""A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text
class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) < 50:
            return self.text
        else:
          return f"{self.text[:50]}..."

MyDjangoProject/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

MyDjangoProject/learning_log/learning_logs/views.py
from django.shortcuts import render, redirect

from learning_logs.models import Topic, Entry

from learning_logs.forms import TopicForm, EntryForm

# Create your views here.

def index(request):
  return render(request, 'learning_logs/index.html')

def topics(request):
  topics = Topic.objects.order_by('date_added')
  context = {'topics':topics}
  return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
  topic = Topic.objects.get(id=topic_id)
  entries = topic.entry_set.order_by('-date_added')
  context = {'topic':topic, 'entries':entries}
  return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
  if request.method != 'POST':
    form = TopicForm()
  else:
    form = TopicForm(data=request.POST)
    if form.is_valid():
      form.save()
      return redirect('learning_logs:topics')
  
  context = {'form': form}
  return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
  topic = Topic.objects.get(id=topic_id)
  
  if request.method!= 'POST':
    form = EntryForm()
  else:
    form = EntryForm(data=request.POST)
    if form.is_valid():
      new_entry = form.save(commit=False)
      new_entry.topic = topic
      new_entry.save()
      return redirect('learning_logs:topic', topic_id=topic_id)

  context = {'topic':topic, 'form':form}
  return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
  entry = Entry.objects.get(id=entry_id)
  topic = entry.topic      

  if request.method != 'POST':
    form = EntryForm(instance=entry)
  else:
    fomr = EntryForm(instance=entry, data=request.POST)
    if form.is_valid():
      form.save()
      return redirect('learning_logs:topic', topic_id=topic.id)
  
  context = {'entry':entry, 'topic':topic, 'form':form}
  return render(request, 'learning_logs/edit_entry.html', context)

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/base.html
<p>
  
  <a href="{% url 'learning_logs:index' %}">Learning Log</a> 
  - <a href="{% url 'learning_logs:topics' %}">Topics</a>

</p>

{% block content %} {% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Learning Log helps you keep track of your learning, 
    for any topic you're interested in. </p>
{% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
  </p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
  </form>

{% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Add a new topic:</p>

  <form action={% url 'learning_logs:new_topic' %} method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Add topic</button>
  </form>

{% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topic: {{topic}}</p>

  <p>Entries:</p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>  
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{entry.text|linebreaks}}</p>
        <p>
          <a href="{% url "learning_logs:edit_entry" entry.id %}">Edit entry</a></p>
        </p>
      </li>
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}

MyDjangoProject/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a></p>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}